name: Metrik-Feedback-System

on: [push]

jobs:
  codequality:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java 19 einrichten
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Analyse-Tool von GitLab herunterladen
        run: |
          curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" -L -o feedback.jar "https://projectbase.medien.hs-duesseldorf.de/api/v4/projects/1089/packages/generic/feedback-tool/1.0.0/feedback.jar"

      - name: Analyse ausführen
        run: java -jar feedback.jar "src/main/java"
        continue-on-error: true

      - name: Dashboard als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-html
          path: dashboard.html